---
title: DMT01
subtitle: Demographics and Baseline Characteristics
format: 
  html:
    code-fold: true
    code-summary: "View Code"
---

::: panel-tabset
## Setup

```{r setup, message=FALSE}
#| code-fold: false
# Load libraries & data -------------------------------------
library(dplyr)
library(gtsummary)

adsl <- pharmaverseadam::adsl |>
  # removing screen failure observations
  filter(TRT01A != "Screen Failure") |>
  # Adding a numeric biomarker (weight)
  left_join(
    pharmaverseadam::advs |>
      filter(VSTESTCD == "WEIGHT", VISIT == "BASELINE") |>
      select(USUBJID, WEIGHTBL = AVAL),
    by = "USUBJID",
    relationship = "one-to-one"
  )


# Pre-processing --------------------------------------------
# Filter for the safety population, x
data <- adsl |>
  filter(SAFFL == "Y")
```

## {gtsummary} Table First

::: panel-tabset
### Table
```{r tbl}
#| message: false
#| warning: false
#| attr-output: 'style="max-height: 400px; overflow-y: auto;"'

tbl <- data |>
  tbl_summary(
    by = "TRT01A",
    include = c("SEX", "AGE", "AGEGR1", "ETHNIC", "RACE"),
    type = all_continuous() ~ "continuous2",
    statistic = list(
      all_continuous() ~ c("{mean} ({sd})", "{median} ({min}, {max})"),
      all_categorical() ~ "{n} ({p}%)"
    ),
    label = list(AGEGR1 = "Age Group, Years")
  ) |>
  add_overall(last = TRUE, col_label = "**Total Population** \nN = {N}") |>
  remove_footnote_header(columns = everything())

tbl
```

### ARD
```{r ard, message=FALSE, results='hide'}
ard <- gather_ard(tbl)
ard
```

```{r, echo=FALSE}
#| attr-output: 'style="max-height: 300px; overflow-y: auto;"'

withr::local_options(width = 9999)
cat("$ tbl_summary\n")
print(as.data.frame(ard$tbl_summary), right = FALSE, row.names = FALSE)
cat("$ add_overall\n")
print(as.data.frame(ard$add_overall), right = FALSE, row.names = FALSE)
```
::: 
:::
